it_stopwords = {'mediante', "un'", 'qualche', 'tu', 'tua', 'giorno', 'effettivamente',
                'trenta', 'fare', 'dagli', 'al', 'seguente', 'stemmo', 'era', 'affinche',
                'sue', 'cogli', 'fanno', 'allo', 'conciliarsi', 'haha', 'stavano', 'tanto',
                'voi', 'certe', 'facesse', "gl'", 'sarai', 'tutta', 'coloro', 'oggi', 'quale',
                'stata', 'sembri', 'giacche', 'neppure', 'fossi', 'no', 'qualunque', 'da',
                'fosti', 'altri', 'parte', 'brava', 'faceste', 'generale', 'partendo', 'noi',
                'è', 'press', 'qualcosa', 'stava', 'tutte', 'della', 'stia', "nessun'", 'sono',
                "d'", 'tuttavia', 'dal', 'foste', 'sugli', 'saremo', 'nessuno', 'od', 'facesti',
                "nient'", 'uguali', 'sarebbero', 'avreste', 'nostri', 'sara', 'paese', 'facevate',
                'fece', 'esempio', 'intanto', 'perfino', 'insieme', 'stesse', 'invece', 'cortesia',
                'avrà', 'dire', 'mancanza', 'soltanto', 'salvo', 'ciascuno', 'non', 'stessimo', 'in',
                'questa', 'avesti', 'anticipo', 'codesti', 'erano', 'circa', 'magari', 'dai', 'all',
                'registrazione', 'dovunque', 'avrebbe', 'nessuna', 'stesti', 'sul', 'trovato', 'faceva',
                'entrambi', 'inoltre', 'ecco', 'stavo', 'fin', 'state', 'abbastanza', 'ansa', 'parecchie',
                'nonsia', 'subito', 'tale', 'lo', 'accidenti', 'nemmeno', 'detto', 'srl', 'come', 'nonostante',
                'avresti', 'starai', 'ognuna', 'degl', 'facciamo', 'avrei', 'percio', 'nel', 'dunque', "dell'",
                'solito', 'talvolta', "quel'", 'facessi', 'avente', 'eppure', 'nostra', 'malissimo', 'facemmo',
                'benissimo', 'staranno', 'lontano', 'suoi', 'aveste', 'prima', 'fatto', 'oltre', 'fareste', 'cioe',
                'mai', 'novanta', 'stette', 'ne', 'abbiano', 'avute', 'hanno', 'di', 'gli', 'chicchessia', 'siano',
                'lato', 'peggio', 'dice', 'titolo', 'due', 'fu', 'presa', 'stessi', 'sullo', 'fino', 'essendo',
                'stareste', 'poi', 'cosi', 'seguito', "dall'", 'avranno', 'medesimo', 'dello', 'potrebbe',
                'fine', 'facendo', 'starete', 'dallo', 'avremo', 'volte', 'degli', 'avessi', 'starei', 'fossero',
                'sembra', 'verso', 'ho', 'ottanta', 'abbiamo', 'facciate', 'inc', 'del', 'assai', 'nostro',
                'contro', 'spesso', 'lavoro', 'nella', 'altro', 'stiate', 'glielo', 'ma', 'marche', 'quanta',
                'quindi', 'negl', 'via', 'stetti', 'bene', 'fuori', 'avevano', 'nostre', 'facciano', 'delle',
                'fra', 'ora', 'là', 'quanti', 'sto', 'nulla', 'perciò', 'faresti', 'saranno', 'dappertutto',
                'quali', 'poiche', 'nazionale', 'sareste', 'solo', 'sarà', 'cos', 'dall', 'averlo', 'sei',
                'avevo', 'governo', 'pure', 'avemmo', 'aveva', 'su', 'nelle', 'vale', 'va', 'finalmente',
                'vicino', 'diventare', 'negli', 'città', 'avevamo', 'hai', 'anno', 'niente', 'forza', 'sui',
                'gliela', 'nell', 'lungo', 'abbia', 'stiamo', 'colei', "l'", 'nei', 'loro', 'nove', 'nuovo',
                'alle', 'sempre', 'questo', 'davanti', 'tutto', 'vari', 'avrebbero', 'staremo', 'col', "c'",
                'esser', 'vita', 'nondimeno', 'realmente', 'tempo', 'allora', 'colui', 'facessimo', 'ieri',
                'stesso', 'vi', 'furono', 'probabilmente', 'quasi', 'sarei', 'stai', 'concernente', 'farà',
                'starebbe', 'siete', 'avessimo', 'aver', 'avrai', 'così', 'macche', 'ulteriore', 'momento',
                'altrimenti', 'mie', 'diventato', 'milioni', 'grazie', 'agl', 'nessun', 'alcuno', 'uomo',
                'ahimè', 'possa', 'tali', 'avrete', 'anni', 'quelli', 'maggior', 'vostra', 'proprio', 'avere',
                "t'", 'cosa', 'principalmente', "quest'", 'miliardi', 'ai', 'mosto', 'qui', 'ancora', 'tre',
                'saresti', 'mesi', 'facessero', 'meno', 'avete', 'preferibilmente', 'stavate', 'quelle', 'siamo',
                'stavi', 'infatti', 'perché', 'piglia', 'improvviso', 'starò', 'già', 'stessero', 'ad', 'però',
                'abbiate', 'certi', 'avesse', 'facevano', 'staremmo', 'alla', 'troppo', 'piedi', 'attraverso',
                'me', 'faccia', 'più', 'anche', 'primo', 'steste', 'vostre', 'farai', 'consiglio', 'starebbero',
                'gia', 'po', 'avessero', 'osi', 'ero', 'un', 'farebbe', 'sette', 'modo', 'tuoi', 'favore', 'cima',
                'ministro', 'miei', 'avuti', 'possedere', 'essi', 'citta', 'faranno', 'saremmo', 'pochissimo',
                'poco', 'piu', 'starà', 'perche', 'riecco', 'stettero', 'sarete', 'mondo', 'intorno', 'staresti',
                'a', 'sull', 'quantunque', 'vostro', 'moltissimo', 'eravate', 'ecc', 'ore', 'lasciato', 'quanto',
                'parecchio', 'tue', 'successivamente', 'chiunque', 'co', 'posteriore', 'relativo', 'gliele',
                'facevamo', 'quest', 'avremmo', 'altrove', 'senza', 'peccato', 'forse', 'per', 'cominci', 'fossimo',
                'se', 'mio', "s'", 'male', 'farebbero', 'certa', 'si', 'diventa', 'pieno', 'coi', 'questi', 'sua',
                'stanno', 'farei', 'ella', 'persone', 'piuttosto', 'successivo', 'sta', 'sotto', 'ultimo', 'gruppo',
                'coll', 'fosse', 'sulle', 'mia', 'che', 'pero', 'quante', 'molto', 'mentre', 'stessa', "m'", 'dovra',
                'ossia', 'quattro', 'varie', 'certo', 'saro', 'scola', 'sopra', 'con', 'sarò', 'la', 'fa', 'ci',
                'agli', 'deve', 'facevi', 'sembrare', 'stiano', 'faccio', 'scorso', 'scopo', 'casa', "v'", 'dentro',
                'fummo', 'vostri', 'egli', 'feci', 'malgrado', 'durante', 'ti', 'tranne', 'posto', 'alcuna',
                'essere', 'li', 'ha', 'dei', 'dietro', 'sig', 'lui', 'stato', 'dagl', 'ogni', 'eravamo', 'secondo',
                'recentemente', 'eri', 'facevo', 'avevi', 'faremo', 'quella', 'finche', 'avuta', 'ebbero', 'basta',
                'oppure', 'esse', 'farete', 'avevate', 'mi', 'comunque', 'dirimpetto', 'fai', 'fecero', 'futuro',
                'cento', 'tutti', 'giorni', 'otto', 'sulla', 'visto', 'ed', 'dovrà', 'quel', 'conclusione', 'mila',
                'persino', 'siate', 'stavamo', 'alcuni', 'ex', 'attesa', 'parecchi', 'fui', 'può', 'dov', 'vario',
                'avendo', 'dalla', 'dopo', 'quello', 'il', 'molti', 'dalle', 'puo', 'adesso', 'lei', 'mezzo',
                'stando', 'suo', 'bravo', 'dove', 'uno', 'grande', 'ahime', 'ciascuna', 'te', 'frattempo',
                'io', 'queste', 'purtroppo', 'faremmo', 'caso', 'codesta', 'chi', 'sarebbe', 'avanti',
                'cui', 'gliene', 'varia', 'cio', 'stati', 'sembrato', 'tra', 'qualcuna', 'codesto',
                'qualcuno', 'volta', 'tuo', 'le', 'recente', 'quando', 'sia', 'nello', 'minimi', 'avrò',
                'e', 'luogo', 'glieli', 'sugl', 'una', 'ognuno', 'farò', 'meglio', 'avuto', 'dell',
                'altrui', 'ebbe', 'ebbi'}
